### ISSUE TITLE
runStudent.py child exception problem

### ISSUE THREAD

**Issue by raywu0123** [music960633/DSnP_grading#1]
嗨助教 
我執行runRef.py沒問題 有成功生出output
但是執行runStudent.py遇到下面這個error

```
python2 py/runStudent.py testcase/case_list.json student/
student_list.json -p 1
Traceback (most recent call last):
  File "py/runStudent.py", line 83, in <module>
    main()
  File "py/runStudent.py", line 78, in main
    runStudent(student_list, case_list, args.parallel_num)
  File "py/runStudent.py", line 54, in runStudent
    runner.run()
  File "/home/ray/CLionProjects/DSnP/DSnP_grading-master/py/utils/task_runner.py", line 67, in run
    task = Task(cmd, cwd, out_filename, time_limit, mem_limit)
  File "/home/ray/CLionProjects/DSnP/DSnP_grading-master/py/utils/task_runner.py", line 21, in __init__
    cwd = cwd)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by music960633** [comment]
Hi, 你有把你的程式放到 <student_id>_fraig 資料夾，還有更新 student_list.json 嗎？這個 error 看起來是因為他找不到要執行的檔案

**Comment by raywu0123** [comment]
喔喔 原來是要複製bin裡面的fraig
